# Only add packages that are Node.js projects
packages:
  - subsystem/aggrada-core
  - subsystem/aggrada-ingestor
  - subsystem/aggrada-outsource
  - subsystem/aggrada-aggregator
  - subsystem/api
  - subsystem/app
  - subsystem/postgresdb
