# Only add packages that are Node.js projects
packages:
  - subsystem/app
  - subsystem/api
  - subsystem/postgresdb
  - subsystem/aggrada-core
  - subsystem/aggrada-outsource
  - subsystem/aggrada-ingestion
  - subsystem/aggrada-aggregator